mode: "development"
port: 8081
name: "MyApp"
version: "1.0.0"
start_time: "2024-01-01T00:00:00Z"
machine_id: 1
log:
  level: "info"
  filename: "app.log"
  max_size: 10
  max_age: 30
  max_backups: 5
mysql:
  host: "mysql8019"
  user: "root"
  password: "root1234"
  dbname: "bluebell-plus"
  port: 3306
  max_open_conns: 100
  max_idle_conns: 50
redis:
  host: "redis507"
  password:
  port: 6379
  db: 0
  pool_size: 10
  min_idle_conns: 5